# Generated by Django 3.1.5 on 2021-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caption',
            field=models.TextField(max_length=500),
        ),
    ]
